# -*- coding: utf-8 -*-
"""Bank customers Survival.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_gTnow7OXB7enh0yLqGh_5YVrSRr6a_

**This data set contains details of a bank's customers and the target variable is a binary variable reflecting the fact whether the customer left the bank (closed his account) or he continues to be a customer.**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/drive/My Drive/my pipe line projects/Churn_Modelling.csv')

df

df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

df

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['Gender']=le.fit_transform(df['Gender'])

df

df=pd.get_dummies(df,drop_first=True)

x=df.drop('Exited',axis=1)

y=df['Exited']

x

x.shape[1:]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=40)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

import keras

from keras.layers import Dense
from keras.layers import Dropout

model=keras.Sequential()

model.add(Dense(units=10,activation='relu',kernel_initializer='he_uniform',input_shape=x.shape[1:]))

model.add(Dense(units=6,activation='relu',kernel_initializer='he_uniform'))
model.add(Dense(units=1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,batch_size=10,epochs=100,validation_split=.25)

